# Generated by Django 6.0.6 on 2026-07-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre / Razón Social')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de Envío')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Artículo')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario Base')),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Impuesto %')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True, verbose_name='Número de Factura')),
                ('emisor_name', models.CharField(max_length=150, verbose_name='Emisor')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('condicion_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Condición de Pago')),
                ('terminos_condiciones', models.TextField(default='El pago debe realizarse dentro de los 15 días...')),
                ('descuento_global', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Descuento ($)')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='facturas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario_historico', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto_historico', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturas.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturas.producto')),
            ],
        ),
    ]
