# Generated by Django 6.0.6 on 2026-07-02 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='porcentaje_impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Impuesto Global (%)'),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.factura'),
        ),
    ]
